# Generated by Django 2.1 on 2023-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewd',
            name='styl_cd',
            field=models.CharField(default='', max_length=50),
        ),
    ]
